### PR TITLE
fix urls in package.json

### PR DESCRIPTION
**Pull request by kremalicious**
Fixes all the urls in `package.json` so the links on our npm registry page are pointing to correct repo. Additionally, fill author field and add npm package badge to readme.

### CODE REVIEW

**Comment by hassansin** [comment]
You can try this https://badge.fury.io/for/js/chartmogul-node, will match the color with Travis badge

**Comment by hassansin** [comment]
Also, would be nice to add a test coverage badge from https://coveralls.io/.

**Comment by kremalicious** [comment]
cool, awesome tip with fury.io-based badge, thanks! We're not setting up test coverage right now so we'll save that badge for later.

**Comment by promulo** [comment]
lgtm :+1:

**Comment by jasonl** [comment]
:+1:

**Pull request merged**
